before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - "darwin"
      - "freebsd"
      - "linux"
      - "windows"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates:
      - "ghcr.io/jimeh/shortmarks:{{ .Version }}-amd64"
      - "ghcr.io/jimeh/shortmarks:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/jimeh/shortmarks:{{ .Version }}-386"
      - "ghcr.io/jimeh/shortmarks:latest-386"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goos: linux
    goarch: "386"
    build_flag_templates:
      - "--platform=linux/386"
  - image_templates:
      - "ghcr.io/jimeh/shortmarks:{{ .Version }}-arm64"
      - "ghcr.io/jimeh/shortmarks:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/jimeh/shortmarks:{{ .Version }}-armv6"
      - "ghcr.io/jimeh/shortmarks:latest-armv6"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - image_templates:
      - "ghcr.io/jimeh/shortmarks:{{ .Version }}-armv7"
      - "ghcr.io/jimeh/shortmarks:latest-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm/v7"

docker_manifests:
  - name_template: ghcr.io/jimeh/shortmarks:{{ .Version }}
    image_templates:
      - ghcr.io/jimeh/shortmarks:{{ .Version }}-amd64
      - ghcr.io/jimeh/shortmarks:{{ .Version }}-386
      - ghcr.io/jimeh/shortmarks:{{ .Version }}-arm64
      - ghcr.io/jimeh/shortmarks:{{ .Version }}-armv6
      - ghcr.io/jimeh/shortmarks:{{ .Version }}-armv7
  - name_template: ghcr.io/jimeh/shortmarks:latest
    image_templates:
      - ghcr.io/jimeh/shortmarks:latest-amd64
      - ghcr.io/jimeh/shortmarks:latest-386
      - ghcr.io/jimeh/shortmarks:latest-arm64
      - ghcr.io/jimeh/shortmarks:latest-armv6
      - ghcr.io/jimeh/shortmarks:latest-armv7
